"""add member decision fields

Revision ID: b10aaa03eff4
Revises: 5f60c30665a2
Create Date: 2026-01-31 23:08:18.498861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b10aaa03eff4'
down_revision: Union[str, Sequence[str], None] = '5f60c30665a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('decision_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('decision_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_members_decision_by', 'admin_users', ['decision_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_members_decision_by', type_='foreignkey')
        batch_op.drop_column('decision_notes')
        batch_op.drop_column('decision_by_admin_id')
        batch_op.drop_column('decision_at')

    # ### end Alembic commands ###
