"""Initial baseline

Revision ID: dc0dd11f634f
Revises:
Create Date: 2026-01-31 05:09:18.803507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0dd11f634f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('statute_version', sa.String(), nullable=True),
    sa.Column('statute_pdf_path', sa.String(), nullable=True),
    sa.Column('privacy_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', name='adminrole'), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_id'), ['id'], unique=False)

    op.create_table('card_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('start_no', sa.Integer(), nullable=True),
    sa.Column('end_no', sa.Integer(), nullable=True),
    sa.Column('next_no', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_batches_id'), ['id'], unique=False)

    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('fiscal_code', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'PENDING_DOCS', 'PENDING_CARDS', 'ACTIVE', name='memberstatus'), nullable=True),
    sa.Column('card_no', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_statute_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_statute_version', sa.String(), nullable=True),
    sa.Column('accepted_privacy_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_privacy_version', sa.String(), nullable=True),
    sa.Column('signup_ip', sa.String(), nullable=True),
    sa.Column('signup_user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['card_batches.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'card_no', name='uix_org_card')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_id'), ['id'], unique=False)

    op.create_table('org_admin_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_admin_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_admin_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_admin_tokens_token_hash'), ['token_hash'], unique=False)

    op.create_table('card_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('card_no', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('paid_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('card_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_card_movements_id'), ['id'], unique=False)

    op.create_table('member_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=True),
    sa.Column('rel_path', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_documents_id'), ['id'], unique=False)

    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.Enum('SIGNUP_CONTINUE', 'LOGIN_MAGIC_LINK', name='tokentype'), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tokens_token_hash'), ['token_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_tokens_id'))

    op.drop_table('tokens')
    with op.batch_alter_table('member_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_documents_id'))

    op.drop_table('member_documents')
    with op.batch_alter_table('card_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_movements_id'))

    op.drop_table('card_movements')
    with op.batch_alter_table('org_admin_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_admin_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_org_admin_tokens_id'))

    op.drop_table('org_admin_tokens')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_id'))
        batch_op.drop_index(batch_op.f('ix_members_email'))

    op.drop_table('members')
    with op.batch_alter_table('card_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_batches_id'))

    op.drop_table('card_batches')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_id'))
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
