export type ForeignBirthPlace = {
  code: string;
  name: string;
};

export const FOREIGN_BIRTH_PLACES: ForeignBirthPlace[] = [
  { code: "Z100", name: "Albania" },
  { code: "Z101", name: "Andorra" },
  { code: "Z102", name: "Austria" },
  { code: "Z103", name: "Belgio" },
  { code: "Z104", name: "Bulgaria" },
  { code: "Z106", name: "Città del Vaticano" },
  { code: "Z149", name: "Croazia" },
  { code: "Z107", name: "Danimarca" },
  { code: "Z144", name: "Estonia" },
  { code: "Z109", name: "Finlandia" },
  { code: "Z110", name: "Francia" },
  { code: "Z136", name: "Georgia" },
  { code: "Z112", name: "Germania" },
  { code: "Z114", name: "Gran Bretagna" },
  { code: "Z115", name: "Grecia" },
  { code: "Z116", name: "Irlanda" },
  { code: "Z117", name: "Islanda" },
  { code: "Z152", name: "Kazakistan" },
  { code: "Z142", name: "Kirghizistan" },
  { code: "Z145", name: "Lettonia" },
  { code: "Z146", name: "Lituania" },
  { code: "Z119", name: "Liechtenstein" },
  { code: "Z120", name: "Lussemburgo" },
  { code: "Z148", name: "Macedonia" },
  { code: "Z121", name: "Malta" },
  { code: "Z140", name: "Moldavia" },
  { code: "Z123", name: "Monaco" },
  { code: "Z125", name: "Norvegia" },
  { code: "Z126", name: "Paesi Bassi" },
  { code: "Z127", name: "Polonia" },
  { code: "Z128", name: "Portogallo" },
  { code: "Z156", name: "Repubblica Ceca" },
  { code: "Z129", name: "Romania" },
  { code: "Z154", name: "Russia" },
  { code: "Z130", name: "San Marino" },
  { code: "Z155", name: "Slovacchia" },
  { code: "Z150", name: "Slovenia" },
  { code: "Z131", name: "Spagna" },
  { code: "Z132", name: "Svezia" },
  { code: "Z133", name: "Svizzera" },
  { code: "Z151", name: "Turkmenistan" },
  { code: "Z138", name: "Ucraina" },
  { code: "Z134", name: "Ungheria" },
  { code: "Z143", name: "Uzbekistan" },
  { code: "Z200", name: "Afghanistan" },
  { code: "Z203", name: "Arabia Saudita" },
  { code: "Z204", name: "Bahrein" },
  { code: "Z249", name: "Bangladesh" },
  { code: "Z205", name: "Bhutan" },
  { code: "Z207", name: "Brunei" },
  { code: "Z208", name: "Cambogia" },
  { code: "Z210", name: "Cina" },
  { code: "Z211", name: "Cipro" },
  { code: "Z213", name: "Corea del Sud" },
  { code: "Z214", name: "Corea del Nord" },
  { code: "Z215", name: "Emirati Arabi Uniti" },
  { code: "Z216", name: "Filippine" },
  { code: "Z219", name: "Giappone" },
  { code: "Z220", name: "Giordania" },
  { code: "Z221", name: "Hong Kong" },
  { code: "Z222", name: "India" },
  { code: "Z223", name: "Indonesia" },
  { code: "Z224", name: "Iran" },
  { code: "Z225", name: "Iraq" },
  { code: "Z226", name: "Israele" },
  { code: "Z227", name: "Kuwait" },
  { code: "Z228", name: "Laos" },
  { code: "Z229", name: "Libano" },
  { code: "Z247", name: "Malaysia" },
  { code: "Z232", name: "Maldive" },
  { code: "Z233", name: "Mongolia" },
  { code: "Z234", name: "Nepal" },
  { code: "Z235", name: "Oman" },
  { code: "Z236", name: "Pakistan" },
  { code: "Z237", name: "Qatar" },
  { code: "Z209", name: "Sri Lanka" },
  { code: "Z240", name: "Siria" },
  { code: "Z241", name: "Thailandia" },
  { code: "Z243", name: "Turchia" },
  { code: "Z246", name: "Yemen" },
  { code: "Z251", name: "Vietnam" },
  { code: "Z301", name: "Algeria" },
  { code: "Z302", name: "Angola" },
  { code: "Z305", name: "Burundi" },
  { code: "Z306", name: "Camerun" },
  { code: "Z307", name: "Capo Verde" },
  { code: "Z309", name: "Ciad" },
  { code: "Z310", name: "Comore" },
  { code: "Z311", name: "Congo" },
  { code: "Z312", name: "Repubblica Democratica del Congo" },
  { code: "Z313", name: "Costa d'Avorio" },
  { code: "Z361", name: "Gibuti" },
  { code: "Z336", name: "Egitto" },
  { code: "Z368", name: "Eritrea" },
  { code: "Z315", name: "Etiopia" },
  { code: "Z316", name: "Gabon" },
  { code: "Z317", name: "Gambia" },
  { code: "Z318", name: "Ghana" },
  { code: "Z319", name: "Guinea" },
  { code: "Z320", name: "Guinea Bissau" },
  { code: "Z321", name: "Guinea Equatoriale" },
  { code: "Z322", name: "Kenya" },
  { code: "Z325", name: "Liberia" },
  { code: "Z326", name: "Libia" },
  { code: "Z327", name: "Madagascar" },
  { code: "Z328", name: "Malawi" },
  { code: "Z329", name: "Mali" },
  { code: "Z330", name: "Marocco" },
  { code: "Z331", name: "Mauritania" },
  { code: "Z332", name: "Maurizio" },
  { code: "Z333", name: "Mozambico" },
  { code: "Z300", name: "Namibia" },
  { code: "Z334", name: "Niger" },
  { code: "Z335", name: "Nigeria" },
  { code: "Z338", name: "Ruanda" },
  { code: "Z342", name: "Seychelles" },
  { code: "Z343", name: "Senegal" },
  { code: "Z344", name: "Sierra Leone" },
  { code: "Z345", name: "Somalia" },
  { code: "Z347", name: "Sudafrica" },
  { code: "Z348", name: "Sudan" },
  { code: "Z349", name: "Swaziland" },
  { code: "Z357", name: "Tanzania" },
  { code: "Z351", name: "Togo" },
  { code: "Z352", name: "Tunisia" },
  { code: "Z353", name: "Uganda" },
  { code: "Z355", name: "Zambia" },
  { code: "Z358", name: "Botswana" },
  { code: "Z359", name: "Lesotho" },
  { code: "Z400", name: "Bermude" },
  { code: "Z401", name: "Canada" },
  { code: "Z402", name: "Groenlandia" },
  { code: "Z404", name: "Stati Uniti d'America" },
  { code: "Z502", name: "Bahamas" },
  { code: "Z522", name: "Barbados" },
  { code: "Z512", name: "Belize" },
  { code: "Z503", name: "Costa Rica" },
  { code: "Z504", name: "Cuba" },
  { code: "Z505", name: "Repubblica Dominicana" },
  { code: "Z506", name: "El Salvador" },
  { code: "Z507", name: "Giamaica" },
  { code: "Z509", name: "Guatemala" },
  { code: "Z510", name: "Haiti" },
  { code: "Z511", name: "Honduras" },
  { code: "Z514", name: "Messico" },
  { code: "Z515", name: "Nicaragua" },
  { code: "Z516", name: "Panama" },
  { code: "Z518", name: "Puerto Rico" },
  { code: "Z524", name: "Grenada" },
  { code: "Z600", name: "Argentina" },
  { code: "Z601", name: "Bolivia" },
  { code: "Z602", name: "Brasile" },
  { code: "Z603", name: "Cile" },
  { code: "Z604", name: "Colombia" },
  { code: "Z605", name: "Ecuador" },
  { code: "Z606", name: "Guyana" },
  { code: "Z607", name: "Guayana Francese" },
  { code: "Z610", name: "Paraguay" },
  { code: "Z611", name: "Peru" },
  { code: "Z612", name: "Trinidad e Tobago" },
  { code: "Z613", name: "Uruguay" },
  { code: "Z614", name: "Venezuela" },
  { code: "Z700", name: "Australia" },
  { code: "Z704", name: "Figi" },
  { code: "Z706", name: "Guam" },
  { code: "Z713", name: "Nauru" },
  { code: "Z716", name: "Nuova Caledonia" },
  { code: "Z719", name: "Nuova Zelanda" },
  { code: "Z723", name: "Polinesia" },
  { code: "Z724", name: "Salomone" },
  { code: "Z725", name: "Samoa Americane" },
  { code: "Z726", name: "Samoa" },
  { code: "Z728", name: "Tonga" },
  { code: "Z730", name: "Papua Nuova Guinea" },
  { code: "Z734", name: "Palau" },
  { code: "Z735", name: "Micronesia" },
].sort((left, right) => left.name.localeCompare(right.name, "it"));

export function findForeignBirthPlaceByCode(code: string): ForeignBirthPlace | undefined {
  const normalized = code.trim().toUpperCase();
  return FOREIGN_BIRTH_PLACES.find((item) => item.code === normalized);
}
